#!/bin/sh
#have replaced pup_event_frontend_d script with compiled daemon.
#this script is called from $HOME/.xinitrc

[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@}

[ -z "$HOMEUSER" ] && . /bin/gethome inittab export

exec /usr/local/pup_event/pup_event_frontend_d

###END###
